// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Vertigo.Json")>]
[<assembly: AssemblyProductAttribute("Vertigo.Json")>]
[<assembly: AssemblyDescriptionAttribute("F# JSON (de)serialization library")>]
[<assembly: AssemblyVersionAttribute("0.1.65.3")>]
[<assembly: AssemblyFileVersionAttribute("0.1.65.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Vertigo.Json"
    let [<Literal>] AssemblyProduct = "Vertigo.Json"
    let [<Literal>] AssemblyDescription = "F# JSON (de)serialization library"
    let [<Literal>] AssemblyVersion = "0.1.65.3"
    let [<Literal>] AssemblyFileVersion = "0.1.65.3"
    let [<Literal>] AssemblyConfiguration = "Release"
